# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"base_request": "00_API.ipynb",
         "auth_header": "00_API.ipynb",
         "fetch_user_data": "00_API.ipynb",
         "get_user_id": "00_API.ipynb",
         "fetch_publications": "00_API.ipynb",
         "post_article": "00_API.ipynb",
         "post_image": "00_API.ipynb",
         "WriteMarkdown": "01_convert.ipynb",
         "HidePreprocessor": "01_convert.ipynb",
         "check_gh_auth": "01_convert.ipynb",
         "upload_gist": "01_convert.ipynb",
         "GisterPreprocessor": "01_convert.ipynb",
         "ImagePreprocessor": "01_convert.ipynb",
         "nb2medium": "02_upload.ipynb"}

modules = ["API.py",
           "convert.py",
           "upload.py"]

doc_url = "https://lc5415.github.io/nb2medium/"

git_url = "https://github.com/lc5415/nb2medium/tree/master/"

def custom_doc_links(name): return None
