# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_upload.ipynb (unless otherwise specified).

__all__ = ['nb2medium']

# Cell
import os
from .mediumapi import post_article
from .convert import (
    HidePreprocessor,
    GisterPreprocessor,
    ImagePreprocessor,
    WriteMarkdown,
    init_convert_logger
)
from nbconvert.exporters import MarkdownExporter
from nbconvert.preprocessors import TagRemovePreprocessor

def nb2medium(
    title,
    notebook
):

    init_convert_logger()

    # declare exporter
    m = MarkdownExporter()
    # Hide Preprocessors
    m.register_preprocessor(HidePreprocessor(mode = 'source'), enabled = True)
    m.register_preprocessor(HidePreprocessor(mode = 'output'), enabled = True)
    m.register_preprocessor(HidePreprocessor(mode = 'cell'), enabled = True)
    m.register_preprocessor(
        TagRemovePreprocessor(
            remove_input_tags = ('hide-source',),
            remove_all_outputs_tags = ('hide-output',),
            remove_cell_tags = ('hide-cell',),
            enabled = True)
    )
    # Gister Preprocessors
    m.register_preprocessor(GisterPreprocessor(), enabled = True)
    #Image Preprocessors
    m.register_preprocessor(ImagePreprocessor(), enabled = True)

    # process notebook
    b,r = m.from_filename(notebook)

    # write notebook to Markdown
    path, name = os.path.split(notebook)
    basename, ext = os.path.splitext(name)
    WriteMarkdown(b,r, filename = basename)

    # upload markdown document as medium post
    return post_article(
        title = title,
        content = open(f"{os.path.splitext(notebook)[0]}.md").read()
    )


