package:
  name: nb2medium
  version: 0.0.2
source:
  sha256: 43d7c52492f400aa00d4dcc26fb173dbbfd76b835866ead5ce3c417fd31a1bd4
  url: https://files.pythonhosted.org/packages/14/09/b3c2f03a14d9f078570f263456f0514b52010175897abb7225d01d879b9e/nb2medium-0.0.2.tar.gz
about:
  dev_url: https://lucharo.github.io
  doc_url: https://lucharo.github.io
  home: https://lucharo.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python package and Jupyter extension that enables submitting Medium drafts
    elegantly from a Jupyter Notebook
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - lucharo
requirements:
  host:
  - pip
  - python
  - packaging
  - requests
  - nbconvert
  - pandas
  - lxml
  - beautifulsoup4
  - fastcore
  run:
  - pip
  - python
  - packaging
  - requests
  - nbconvert
  - pandas
  - lxml
  - beautifulsoup4
  - fastcore
test:
  imports:
  - nb2medium
