baseurl: /nb2medium/
collections:
  tooltips:
    output: false
company_name: GPLv3 Licence
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: Python package and Jupyter extension that enables submitting Medium drafts
  elegantly from a Jupyter Notebook
exclude:
- vendor
google_analytics: null
google_search: null
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
output: web
permalink: pretty
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: lc5415/nb2medium
sidebars:
- home_sidebar
site_title: nb2medium
topnav_title: nb2medium
use_math: true
